### ISSUE TITLE
Listing possible use cases in the README

### ISSUE THREAD

**Issue by Rush** [Ravadre/Stacks#3]
This could make the library more available to potential users

**Comment by Ravadre** [comment]
I think that a wiki with more complete samples could give a good idea of how to use this library and why it's different from others, but general use cases are pretty obvious right now, especially that Stacks are not feature complete yet. I'd wait with it till the Api is more stable though, otherwise it might be more confusing than helpful.

**Comment by Rush** [comment]
I was rather thinking of something simple like:

```
You could use this library to develop:
* A
* B
* C 
```

Something that would make google index your github repository for all those use cases being searched for.
